### PR TITLE
refactor: create enum for "action row type" codes

### PR DESCRIPTION
**Pull request by Jameskmonger**
An `ActionRowType` controls the type of action that happens when a user interacts with something

e.g. when interacting with an NPC, the `ActionRowType` will be `12` (now aliased as `NPC_INTERACTION_OPTION_1`)

This PR introduces a named enum for these values, as well as documentation on their purposes, and uses that enum throughout the codebase.

### CODE REVIEW

**Review by SchauweM — APPROVED** [review]
Freaking beautiful

**Comment by Kikorono** [comment]
😍

**Comment by Jameskmonger** [comment]
just following up to confirm: I have looked through all the values manually and checked that I didn't make any mistakes with this PR.

**Comment by Jameskmonger** [comment]
I found this on Rune-Server..

```
2 = TGT_LOC
3 = OP_LOC1
4 = OP_LOC2
5 = OP_LOC3
6 = OP_LOC4
8 = TGT_NPC
9 = OP_NPC1
10 = OP_NPC2
11 = OP_NPC3
12 = OP_NPC4
13 = OP_NPC5
15 = TGT_PLAYER
16 = TGT_SELF
17 = TGT_OBJ
18 = OP_OBJ1
19 = OP_OBJ2
20 = OP_OBJ3
21 = OP_OBJ4
22 = OP_OBJ5
23 = WALK
25 = TGT_BUTTON
30 = PAUSE_BUTTON
44 = OP_PLAYER1
45 = OP_PLAYER2
46 = OP_PLAYER3
47 = OP_PLAYER4
48 = OP_PLAYER5
49 = OP_PLAYER6
50 = OP_PLAYER7
51 = OP_PLAYER8
52 = OP_PLAYER9
53 = OP_PLAYER10
57 = IF_BUTTONX1
58 = IF_BUTTONT
59 = TGT_GROUND
60 = FACE_SQUARE
1001 = OP_LOC5
1002 = OP_LOC6
1003 = OP_NPC6
1004 = OP_OBJ6
1006 = CANCEL
1007 = IF_BUTTONX2
1008 = OP_MAPELEMENT1
1009 = OP_MAPELEMENT2
1010 = OP_MAPELEMENT3
1011 = OP_MAPELEMENT4
1012 = OP_MAPELEMENT5
2009 = OP_NPC1_LOWPRIORITY
2010 = OP_NPC2_LOWPRIORITY
2011 = OP_NPC3_LOWPRIORITY
2012 = OP_NPC4_LOWPRIORITY
2013 = OP_NPC5_LOWPRIORITY
3003 = OP_NPC6_LOWPRIORITY
2044 = OP_PLAYER1_LOWPRIORITY
2045 = OP_PLAYER2_LOWPRIORITY
2046 = OP_PLAYER3_LOWPRIORITY
2047 = OP_PLAYER4_LOWPRIORITY
2048 = OP_PLAYER5_LOWPRIORITY
2049 = OP_PLAYER6_LOWPRIORITY
2050 = OP_PLAYER7_LOWPRIORITY
2051 = OP_PLAYER8_LOWPRIORITY
2052 = OP_PLAYER9_LOWPRIORITY
2053 = OP_PLAYER10_LOWPRIORITY
```

**Comment by Jameskmonger** [comment]
It doesn't line up to our client in terms of IDs but the namings could be used.

**Pull request merged**
