### PR TITLE
Client sided Update Server code renaming / static moving

### PR DESCRIPTION
**Pull request by MatthewBishop**
Moved some static variables/methods and renamed some values associated with the Client Sided Js5 System.

### CODE REVIEW

**Comment by MatthewBishop** [comment]
I do think that the name UpdateServer doesn't really fit well for this class. I would prefer something like Js5Client or Js5Requester.

**Review by Jameskmonger — APPROVED** [review]

**Comment by Jameskmonger** [comment]
Looks good to me, nice work @MatthewBishop

**Comment by MatthewBishop** [comment]
> Looks good to me, nice work @MatthewBishop

Thanks for the review, I figured I would split some of this renaming/refactoring into multiple smaller PRs since they touch a lot of files so that the review is easier.

**Comment by Kikorono** [comment]
LGTM!

**Pull request merged**
